-- ============================================================
-- SISTEMA DE GESTAO DE VISITAS E AGENDAMENTOS
-- Supabase + PostgreSQL + Supabase Auth + RLS
-- ============================================================
--
-- MODELO DE ACESSO:
--
-- USER
--   - consulta seu proprio cadastro
--   - consulta funcoes, locais e tarefas ativos
--   - consulta seus proprios agendamentos
--   - cria agendamentos somente para si
--   - edita somente seus proprios agendamentos
--
-- ADM
--   - consulta todos os usuarios
--   - altera dados complementares dos usuarios
--   - consulta todos os agendamentos
--   - cria/edita agendamentos
--   - gerencia funcoes, locais e tarefas
--
-- IMPORTANTE:
-- Nunca utilizar SERVICE_ROLE no frontend.
-- ============================================================


-- ============================================================
-- 0. EXTENSAO
-- ============================================================

create extension if not exists pgcrypto;


-- ============================================================
-- 1. TABELA FUNCOES
-- ============================================================

create table if not exists public.funcoes (
    id bigint generated by default as identity primary key,
    nome text not null,
    ativo boolean not null default true,

    constraint funcoes_nome_obrigatorio
        check (length(trim(nome)) > 0),

    constraint funcoes_nome_unique
        unique (nome)
);


-- ============================================================
-- 2. TABELA USUARIOS
-- ============================================================

create table if not exists public.usuarios (
    id uuid primary key
        references auth.users(id)
        on delete cascade,

    nome text not null,
    email text not null,
    escopo text not null default 'user',
    funcao_id bigint
        references public.funcoes(id)
        on update cascade
        on delete set null,

    ativo boolean not null default true,
    created_at timestamptz not null default now(),

    constraint usuarios_nome_obrigatorio
        check (length(trim(nome)) > 0),

    constraint usuarios_email_obrigatorio
        check (length(trim(email)) > 0),

    constraint usuarios_escopo_check
        check (lower(trim(escopo)) in ('adm', 'user')),

    constraint usuarios_email_unique
        unique (email)
);


-- ============================================================
-- 3. TABELA LOCAIS
-- ============================================================

create table if not exists public.locais (
    id bigint generated by default as identity primary key,

    nome text not null,
    cidade text not null,
    ativo boolean not null default true,

    constraint locais_nome_obrigatorio
        check (length(trim(nome)) > 0),

    constraint locais_cidade_obrigatoria
        check (length(trim(cidade)) > 0),

    constraint locais_nome_cidade_unique
        unique (nome, cidade)
);


-- ============================================================
-- 4. TABELA TAREFAS
-- ============================================================

create table if not exists public.tarefas (
    id bigint generated by default as identity primary key,

    nome text not null,
    descricao text,
    ativo boolean not null default true,

    constraint tarefas_nome_obrigatorio
        check (length(trim(nome)) > 0),

    constraint tarefas_nome_unique
        unique (nome)
);


-- ============================================================
-- 5. TABELA AGENDAMENTOS
-- ============================================================

create table if not exists public.agendamentos (
    id bigint generated by default as identity primary key,

    usuario_id uuid not null
        references public.usuarios(id)
        on update cascade
        on delete restrict,

    local_id bigint not null
        references public.locais(id)
        on update cascade
        on delete restrict,

    tarefa_id bigint not null
        references public.tarefas(id)
        on update cascade
        on delete restrict,

    data date not null,

    periodo text not null,

    status text not null default 'planejado',

    objetivo text,

    resumo text,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint agendamentos_periodo_check
        check (
            periodo in (
                'manha',
                'tarde',
                'noite'
            )
        ),

    constraint agendamentos_status_check
        check (
            status in (
                'planejado',
                'concluido'
            )
        ),

    -- Uma visita concluida obrigatoriamente precisa de resumo.
    constraint agendamentos_resumo_concluido_check
        check (
            status <> 'concluido'
            or nullif(trim(resumo), '') is not null
        )
);


-- ============================================================
-- 6. INDICES
-- ============================================================

create index if not exists idx_agendamentos_usuario
    on public.agendamentos(usuario_id);

create index if not exists idx_agendamentos_data
    on public.agendamentos(data);

create index if not exists idx_agendamentos_local
    on public.agendamentos(local_id);

create index if not exists idx_agendamentos_status
    on public.agendamentos(status);

create index if not exists idx_agendamentos_periodo
    on public.agendamentos(periodo);

create index if not exists idx_agendamentos_tarefa
    on public.agendamentos(tarefa_id);

create index if not exists idx_agendamentos_usuario_data
    on public.agendamentos(usuario_id, data);

create index if not exists idx_agendamentos_data_local
    on public.agendamentos(data, local_id);

create index if not exists idx_agendamentos_data_local_periodo
    on public.agendamentos(data, local_id, periodo);

create index if not exists idx_usuarios_funcao
    on public.usuarios(funcao_id);

create index if not exists idx_usuarios_ativo
    on public.usuarios(ativo);

create index if not exists idx_locais_cidade
    on public.locais(cidade);


-- ============================================================
-- 7. UPDATED_AT AUTOMATICO
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_agendamentos_updated_at
on public.agendamentos;

create trigger trg_agendamentos_updated_at
before update on public.agendamentos
for each row
execute function public.set_updated_at();


-- ============================================================
-- 8. FUNCOES AUXILIARES DE SEGURANCA
-- ============================================================
--
-- Precisamos consultar o perfil do usuario dentro das policies.
-- Usamos SECURITY DEFINER para evitar recursao das policies
-- da propria tabela usuarios.
--
-- ============================================================

create or replace function public.usuario_e_adm()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.usuarios u
        where u.id = (select auth.uid())
          and u.ativo = true
          and lower(trim(u.escopo)) = 'adm'
    );
$$;

create or replace function public.usuario_esta_ativo()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.usuarios u
        where u.id = (select auth.uid())
          and u.ativo = true
    );
$$;

revoke all on function public.usuario_e_adm() from public;
revoke all on function public.usuario_esta_ativo() from public;

grant execute on function public.usuario_e_adm() to authenticated;
grant execute on function public.usuario_esta_ativo() to authenticated;


-- ============================================================
-- 9. ATIVAR ROW LEVEL SECURITY
-- ============================================================

alter table public.funcoes enable row level security;
alter table public.usuarios enable row level security;
alter table public.locais enable row level security;
alter table public.tarefas enable row level security;
alter table public.agendamentos enable row level security;


-- ============================================================
-- 10. FORCE RLS
-- ============================================================

alter table public.funcoes force row level security;
alter table public.usuarios force row level security;
alter table public.locais force row level security;
alter table public.tarefas force row level security;
alter table public.agendamentos force row level security;


-- ============================================================
-- 11. TRIGGER DE PROTECAO DE CAMPOS ADMINISTRATIVOS
-- ============================================================
--
-- Um usuario comum pode atualizar seu proprio registro (por
-- exemplo, se um dia o sistema permitir editar preferencias),
-- mas jamais pode alterar escopo, funcao ou o proprio status
-- de ativo/inativo. Apenas o ADM pode alterar esses campos.
-- Isso e reforcado aqui via trigger, e nao apenas via RLS,
-- pois RLS nao restringe colunas individualmente.
-- ============================================================

create or replace function public.usuarios_protege_campos_admin()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if coalesce(auth.jwt()->>'role', '') <> 'service_role'
       and not public.usuario_e_adm() then
        new.escopo := old.escopo;
        new.funcao_id := old.funcao_id;
        new.ativo := old.ativo;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_usuarios_protege_campos_admin
on public.usuarios;

create trigger trg_usuarios_protege_campos_admin
before update on public.usuarios
for each row
execute function public.usuarios_protege_campos_admin();


-- ============================================================
-- 12. POLICIES - FUNCOES
-- ============================================================

drop policy if exists funcoes_select on public.funcoes;
create policy funcoes_select
on public.funcoes
for select
to authenticated
using (
    public.usuario_e_adm()
    or (ativo = true and public.usuario_esta_ativo())
);

drop policy if exists funcoes_adm_insert on public.funcoes;
create policy funcoes_adm_insert
on public.funcoes
for insert
to authenticated
with check (public.usuario_e_adm());

drop policy if exists funcoes_adm_update on public.funcoes;
create policy funcoes_adm_update
on public.funcoes
for update
to authenticated
using (public.usuario_e_adm())
with check (public.usuario_e_adm());

drop policy if exists funcoes_adm_delete on public.funcoes;
create policy funcoes_adm_delete
on public.funcoes
for delete
to authenticated
using (public.usuario_e_adm());


-- ============================================================
-- 13. POLICIES - LOCAIS
-- ============================================================

drop policy if exists locais_select on public.locais;
create policy locais_select
on public.locais
for select
to authenticated
using (
    public.usuario_e_adm()
    or (ativo = true and public.usuario_esta_ativo())
);

drop policy if exists locais_adm_insert on public.locais;
create policy locais_adm_insert
on public.locais
for insert
to authenticated
with check (public.usuario_e_adm());

drop policy if exists locais_adm_update on public.locais;
create policy locais_adm_update
on public.locais
for update
to authenticated
using (public.usuario_e_adm())
with check (public.usuario_e_adm());

drop policy if exists locais_adm_delete on public.locais;
create policy locais_adm_delete
on public.locais
for delete
to authenticated
using (public.usuario_e_adm());


-- ============================================================
-- 14. POLICIES - TAREFAS
-- ============================================================

drop policy if exists tarefas_select on public.tarefas;
create policy tarefas_select
on public.tarefas
for select
to authenticated
using (
    public.usuario_e_adm()
    or (ativo = true and public.usuario_esta_ativo())
);

drop policy if exists tarefas_adm_insert on public.tarefas;
create policy tarefas_adm_insert
on public.tarefas
for insert
to authenticated
with check (public.usuario_e_adm());

drop policy if exists tarefas_adm_update on public.tarefas;
create policy tarefas_adm_update
on public.tarefas
for update
to authenticated
using (public.usuario_e_adm())
with check (public.usuario_e_adm());

drop policy if exists tarefas_adm_delete on public.tarefas;
create policy tarefas_adm_delete
on public.tarefas
for delete
to authenticated
using (public.usuario_e_adm());


-- ============================================================
-- 15. POLICIES - USUARIOS
-- ============================================================
--
-- Observacao: os usuarios sao criados no Supabase Auth e a
-- linha correspondente em public.usuarios deve ser inserida
-- manualmente (ou via trigger de signup, fora do escopo desta
-- formacao). Por isso nao existe policy de INSERT para o
-- usuario comum. O ADM pode inserir para cadastrar o
-- complemento de um novo usuario ja existente no Auth.
-- ============================================================

drop policy if exists usuarios_select on public.usuarios;
create policy usuarios_select
on public.usuarios
for select
to authenticated
using (
    id = (select auth.uid())
    or public.usuario_e_adm()
);

drop policy if exists usuarios_adm_insert on public.usuarios;
create policy usuarios_adm_insert
on public.usuarios
for insert
to authenticated
with check (public.usuario_e_adm());

-- Usuario comum pode atualizar seu proprio registro (nome),
-- mas escopo/funcao/ativo sao protegidos pelo trigger acima.
drop policy if exists usuarios_update_self on public.usuarios;
create policy usuarios_update_self
on public.usuarios
for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

-- ADM pode atualizar qualquer usuario (funcao, escopo, ativo).
drop policy if exists usuarios_update_adm on public.usuarios;
create policy usuarios_update_adm
on public.usuarios
for update
to authenticated
using (public.usuario_e_adm())
with check (public.usuario_e_adm());


-- ============================================================
-- 16. POLICIES - AGENDAMENTOS
-- ============================================================

drop policy if exists agendamentos_select on public.agendamentos;
create policy agendamentos_select
on public.agendamentos
for select
to authenticated
using (
    public.usuario_e_adm()
    or (
        usuario_id = (select auth.uid())
        and public.usuario_esta_ativo()
    )
);

-- Usuario comum so pode criar agendamento para si mesmo.
drop policy if exists agendamentos_insert_self on public.agendamentos;
create policy agendamentos_insert_self
on public.agendamentos
for insert
to authenticated
with check (
    usuario_id = (select auth.uid())
    and public.usuario_esta_ativo()
);

-- ADM pode criar agendamento para qualquer usuario.
drop policy if exists agendamentos_insert_adm on public.agendamentos;
create policy agendamentos_insert_adm
on public.agendamentos
for insert
to authenticated
with check (public.usuario_e_adm());

-- Usuario comum so pode editar seus proprios agendamentos.
drop policy if exists agendamentos_update_self on public.agendamentos;
create policy agendamentos_update_self
on public.agendamentos
for update
to authenticated
using (
    usuario_id = (select auth.uid())
    and public.usuario_esta_ativo()
)
with check (
    usuario_id = (select auth.uid())
    and public.usuario_esta_ativo()
);

-- ADM pode editar qualquer agendamento.
drop policy if exists agendamentos_update_adm on public.agendamentos;
create policy agendamentos_update_adm
on public.agendamentos
for update
to authenticated
using (public.usuario_e_adm())
with check (public.usuario_e_adm());

-- Exclusao somente pelo ADM.
drop policy if exists agendamentos_delete_adm on public.agendamentos;
create policy agendamentos_delete_adm
on public.agendamentos
for delete
to authenticated
using (public.usuario_e_adm());


-- ============================================================
-- 17. PERMISSOES (GRANTS)
-- ============================================================
--
-- RLS decide QUAIS linhas cada usuario ve/edita.
-- Os GRANTs abaixo decidem quais OPERACOES a role authenticated
-- pode tentar (a policy ainda filtra linha a linha).
-- Nunca conceder nada a role anon nem usar service_role no
-- frontend.
-- ============================================================

grant usage on schema public to authenticated;

revoke all on table public.usuarios from authenticated;
revoke all on table public.usuarios from service_role;

grant select, insert, update
on public.usuarios
to authenticated;

grant select, insert, update
on public.usuarios
to service_role;

grant select, insert, update, delete
on public.funcoes to authenticated;

grant select, insert, update, delete
on public.locais to authenticated;

grant select, insert, update, delete
on public.tarefas to authenticated;

grant select, insert, update, delete
on public.agendamentos to authenticated;

grant usage on all sequences in schema public to authenticated;


-- ============================================================
-- 18. DADOS INICIAIS (OPCIONAL - AJUSTE CONFORME A REDE)
-- ============================================================

insert into public.funcoes (nome) values
    ('Supervisor'),
    ('CEC'),
    ('PEC'),
    ('Dirigente')
on conflict (nome) do nothing;

insert into public.tarefas (nome, descricao) values
    ('Acompanhamento pedagógico', null),
    ('Apoio presencial', null),
    ('Reunião com coordenação', null),
    ('Reunião com direção', null),
    ('Formação', null),
    ('ATPA', null),
    ('ATPCG', null),
    ('Acompanhamento de avaliação', null)
on conflict (nome) do nothing;

-- Ajuste os locais reais da sua rede de ensino.
insert into public.locais (nome, cidade) values
    ('Escola Estadual João da Silva', 'Valfenda'),
    ('Escola Estadual Maria Souza', 'Mordor'),
    ('URE', 'Condado'),
    ('Sala de formação', 'Condado')
on conflict (nome, cidade) do nothing;
-- ============================================================
-- 19. TRIGGER: AUTO-CRIAR public.usuarios AO CRIAR NO AUTH
-- ============================================================
-- Quando um usuario e criado em Authentication > Users, este
-- trigger insere automaticamente a linha correspondente em
-- public.usuarios, reaproveitando o UUID do Auth.
--
-- O nome inicial vem de raw_user_meta_data->>'nome' (se for
-- informado no cadastro) ou do prefixo do e-mail.
-- ============================================================

create or replace function public.criar_usuario_apos_signup()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.usuarios (id, nome, email)
    values (
        new.id,
        coalesce(
            nullif(trim(new.raw_user_meta_data->>'nome'), ''),
            split_part(new.email, '@', 1)
        ),
        new.email
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists trg_on_auth_user_created on auth.users;

create trigger trg_on_auth_user_created
after insert on auth.users
for each row
execute function public.criar_usuario_apos_signup();

-- ============================================================
-- 20. NOMES DE USUÁRIOS (para USER ver no Consolidado/Calendário)
-- ============================================================
-- RLS é row-level, não column-level. Para o USER ver apenas
-- o NOME dos demais usuários (e não o e-mail), expomos via
-- função SECURITY DEFINER. A policy da tabela usuarios
-- continua restrita (self ou ADM), sem vazar e-mail.
-- ============================================================

create or replace function public.listar_usuarios_ativos()
returns table (id uuid, nome text)
language sql
stable
security definer
set search_path = ''
as $$
    select u.id, u.nome
    from public.usuarios u
    where u.ativo = true
    order by u.nome;
$$;

revoke all on function public.listar_usuarios_ativos() from public;
grant execute on function public.listar_usuarios_ativos() to authenticated;

drop policy if exists agendamentos_select on public.agendamentos;
create policy agendamentos_select
on public.agendamentos
for select
to authenticated
using (public.usuario_esta_ativo());

-- Remove a policy atual (só ADM)
drop policy if exists agendamentos_delete_adm on public.agendamentos;

-- Dono pode excluir o próprio
drop policy if exists agendamentos_delete_self on public.agendamentos;
create policy agendamentos_delete_self
on public.agendamentos
for delete
to authenticated
using (
    usuario_id = (select auth.uid())
    and public.usuario_esta_ativo()
);

-- ADM continua podendo excluir qualquer
drop policy if exists agendamentos_delete_adm on public.agendamentos;
create policy agendamentos_delete_adm
on public.agendamentos
for delete
to authenticated
using (public.usuario_e_adm());

do $$
declare
    tipo_periodo text;
begin
    select format_type(a.atttypid, a.atttypmod)
      into tipo_periodo
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'agendamentos'
      and a.attname = 'periodo'
      and not a.attisdropped;

    if tipo_periodo = 'text' then
        alter table public.agendamentos
            drop constraint if exists agendamentos_periodo_check;
        alter table public.agendamentos
            alter column periodo type text[]
            using array[periodo];
    else
        alter table public.agendamentos
            drop constraint if exists agendamentos_periodo_check;
    end if;

    alter table public.agendamentos
        add constraint agendamentos_periodo_check
        check (
            periodo <@ array['manha','tarde','noite']::text[]
            and array_length(periodo, 1) >= 1
        );

    alter table public.agendamentos
        alter column periodo set default array['manha'];
end;
$$;

-- ============================================================
-- FIM DO SCRIPT
--
-- Apos rodar este SQL:
-- 1. Crie os usuarios em Authentication > Users.
-- 2. Insira o complemento de cada usuario na tabela
--    public.usuarios (id = UUID do Auth, nome, email, escopo).
-- 3. O primeiro usuario ADM deve ser inserido manualmente
--    (via SQL editor ou Table editor), pois so um ADM pode
--    criar outros ADMs pela tela de Cadastro.
-- ============================================================
-- ============================================================
-- 21. PERÍODO MÚLTIPLO (array)
-- ============================================================
-- Antes: periodo text not null, check in ('manha','tarde','noite')
-- Agora: periodo text[] com 1..3 valores válidos
-- ============================================================

-- ============================================================
-- 22. VERIFICACAO FINAL
-- ============================================================
-- Conferir grants:
--
-- select grantee, privilege_type
-- from information_schema.role_table_grants
-- where table_schema = 'public'
--   and table_name = 'usuarios'
--   and grantee in ('authenticated', 'service_role')
-- order by grantee, privilege_type;
--
-- Esperado:
-- authenticated -> INSERT, SELECT, UPDATE
-- service_role  -> INSERT, SELECT, UPDATE
--
-- Conferir RLS:
--
-- select relname, relrowsecurity, relforcerowsecurity
-- from pg_class
-- where relname = 'usuarios';
--
-- Esperado:
-- relrowsecurity = true
-- relforcerowsecurity = true
--
-- IMPORTANTE: SERVICE_ROLE_KEY somente no backend/Edge Functions.
-- ============================================================
